### ISSUE TITLE
这里已经不处理友情链接了，请去discussions里面。

### ISSUE THREAD

**Issue by Ukenn2112** [Fuukei/Sakurairo_Wiki#1]
## 此ISSUE已经停用，请前往Discussions [在主题官方站点展示你的网站 / Show Your Website on the Official Theme Site](https://github.com/Fuukei/Sakurairo_Wiki/discussions/9) 进行申请

如果您正在使用 `「iro」主题`，你可以在这里留下你的站点链接。
我会把它加入示例站点中！
 
 ## 格式
```yaml
"name": "約束の明日へ", 
"url": "https://asuhe.jp", 
"avatar": "https://asuhe.jp/wp-content/uploads/2020/12/logo.png", 
"desc": "また君を思い出すよ" 
```

"name":  ——》# 最好不要太长，控制在八个中文字符宽度内
"url":      ——》 # 站点链接
"avatar": ——》# 你的头像链接，请确保它为正方形或圆形。
"desc":   ——》# 简单描述一下你的站点、或者你喜欢的句子

 其他你想要说的话（畅所欲言～）
 
## 注意:
 * 如果你的站点不再使用 `「iro」主题`，那么你的站点将会被移除。
 * 如果你的站点文章数量较少、存在不适宜内容、内容质量过低，将不会被收录。
 * 如果你的网站在大陆内、外（简称：全球）范围内出现不和访问的国家，那么站点将不会被收录。
 * 如果你移除了底部的版权信息或未遵守 [SATA 协议](https://github.com/zTrix/sata-license)，你可以使用它，但将不会被允许添加至此处。
